language: python
sudo: required
python:
  - "3.5.2"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: python -m pytest FlaskPortal\\Portal_Main\\flask_portal\\TestSuite\\flask_portal_tests.py
